name: Composite action for Terraform plan
description: Runs Terraform plan on selected environment

inputs:
  environment:
    description: The environment where to run the action
    default: 'uat'
  stepName:
    description: The name of the job step to execute and catch output from
    required: true

runs:
  using: "composite"    
  steps:

    - uses: actions/checkout@v4
    - name: Terraform plan
      id: ${{ inputs.stepName }}
      environment: ${{ inputs.environment }}
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/src/terraform
        terraform init -upgrade -backend-config='../../configuration/${{ inputs.environment }}/backend.hcl'
        exitcode=0
        terraform plan -detailed-exitcode -var-file='../../configuration/${{ inputs.environment }}/var.tfvars' -input=false -auto-approve || exitcode=$?
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        if [ $exitcode -eq 1 ]; then
          echo "Error in TF plan - exit"
          exit 1
        fi
      env:
        TF_VAR_admin_account_password : ${{ secrets.admin_account_password }}
        ARM_CLIENT_ID: ${{ vars.SP_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
