name: Composite action for Terraform plan
description: Runs Terraform plan on selected environment

inputs:
  environment:
    description: The environment where to run the action
    default: 'uat'
  tf_src_folder:
    description: Folder containing Terraform template files (absolute path)
    required: true

runs:
  using: "composite"    
  steps:

    - uses: actions/checkout@v4
    - name: terraform_plan_to_${{ inputs.environment }}
      environment: ${{ inputs.environment }}
      shell: pwsh
      env: 
        tf_src_folder: ${{ inputs.tf_src_folder }}
      run: |
        cd $tf_src_folder
        terraform init -upgrade -backend-config='../../configuration/${{ inputs.environment }}/backend.hcl'
        terraform plan -var-file='../../configuration/${{ inputs.environment }}/var.tfvars' -input=false -auto-approve
      env:
        TF_VAR_admin_account_password : ${{ secrets.admin_account_password }}
        ARM_CLIENT_ID: ${{ vars.SP_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
