name: (third) Format Terraform configuration file contents
on:
  workflow_dispatch:
  pull_request:
    branches:
    - dev
  
jobs:

  linter3:
    runs-on: ubuntu-22.04
    name: LinterName3
    steps:

    - uses: actions/checkout@v4
    - name: run fmt command
      shell: pwsh
      run: |
        cd ./src/terraform
        terraform fmt -recursive -check -diff
