name: Release workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main  
    
jobs:

  tf_apply_to_uat:
    uses: ./.github/workflows/tfapply.yaml
    
