name: Reusable workflow for Terraform plan-apply
on:
  workflow_call:
    inputs:
      environment:
        description: The environment where to run the action
        type: string
        default: 'uat'
        required: true
    
jobs:

  TF_plan:
    runs-on: ubuntu-22.04
    name: Terraform plan
    outputs:
      tfPlanExitCode: ${{ steps.tf_plan.outputs.exitcode }}
    steps:

    - uses: ./.github/actions/terraform_plan@main
      with:
        environment: uat # should have required reviewers
        stepName: tf_plan

  TF_apply:
    runs-on: ubuntu-22.04
    name: Terraform apply
    needs:
    - TF_plan
    # only run this step if the previous plan step returned 2 == changes exist in TF plan
    if: needs.TF_plan.outputs.tfPlanExitCode == 2
    steps:

    - uses: ./.github/actions/terraform_apply@main
      with:
        environment: uat
        stepName: tf_apply
